server:
  port : 8081

spring:
  datasource:
    name : druidDataSource
    url : jdbc:mysql://10.215.28.5:3306/dowsing_data?useUnicode=true&characterEncoding=UTF-8
    username : dowsing_data
    password : LU2gGhHx
    type : com.alibaba.druid.pool.DruidDataSource
    driver-class-name : com.mysql.jdbc.Driver
    filters : stat
    maxActive : 60
    initialSize : 10
    maxWait : 60000
    minIdle : 1
    timeBetweenEvictionRunsMillis : 60000
    minEvictableIdleTimeMillis : 300000
    validationQuery : SELECT 1
    testWhileIdle : true
    testOnBorrow : false
    testOnReturn : false
    poolPreparedStatements : false
    maxOpenPreparedStatements : 20

  security :
    user :
      name : dw
      password : dw

  mvc:
    throw-exception-if-no-handler-found : true

  resources:
    add-mappings : false


mybatis:
  configuration:
      map-underscore-to-camel-case: true




