server:
  port : 8081

spring:
  datasource:
    type : com.alibaba.druid.pool.DruidDataSource
    primary :
        name : dowsing
        type : com.alibaba.druid.pool.DruidDataSource
        url : jdbc:mysql://10.215.28.5:3306/ad_report?useUnicode=true&characterEncoding=UTF-8
        username : report
        password : 69PkFs7ty
        driver-class-name : com.mysql.jdbc.Driver
        filters : stat
        maxActive : 60
        initialSize : 10
        maxWait : 60000
        minIdle : 1
        timeBetweenEvictionRunsMillis : 60000
        minEvictableIdleTimeMillis : 300000
        validationQuery : SELECT 1
        testWhileIdle : true
        testOnBorrow : false
        testOnReturn : false
        poolPreparedStatements : false
        maxOpenPreparedStatements : 20
    secondary :
        name : jobs
        type : com.alibaba.druid.pool.DruidDataSource
        url : jdbc:mysql://10.215.28.170:3306/fancy_report_task?useUnicode=true&characterEncoding=UTF-8
        username : report
        password : 69PkFs7ty
        driver-class-name : com.mysql.jdbc.Driver
        filters : stat
        maxActive : 60
        initialSize : 10
        maxWait : 60000
        minIdle : 1
        timeBetweenEvictionRunsMillis : 60000
        minEvictableIdleTimeMillis : 300000
        validationQuery : SELECT 1
        testWhileIdle : true
        testOnBorrow : false
        testOnReturn : false
        poolPreparedStatements : false
        maxOpenPreparedStatements : 20

  security :
    user :
      name : dw
      password : dw

  mvc:
    throw-exception-if-no-handler-found : true

  resources:
    add-mappings : false

  mail :
    host : smtp.qq.com
    username : huangrh@fancydsp.com
    password : ruihua@123
    properties :
      mail :
        smtp :
          auth : true
          starttls :
            enable : false
            required : false

presto :
  connection :
    url : jdbc:presto://10.215.28.121:10080/hive/default
    driver : com.facebook.presto.jdbc.PrestoDriver
    user : spring
    password :

mybatis:
  configuration:
      map-underscore-to-camel-case: true




